Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(main.py:3490629): Gdk-CRITICAL **: 15:50:54.402: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed

(main.py:3490629): Gdk-CRITICAL **: 15:50:54.403: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Traceback (most recent call last):
  File "main.py", line 364, in <module>
    exp_chain = MarkovChain(slow_reversible_propose_bi ,Validator([single_flip_contiguous, popbound#,boundary_condition
NameError: name 'popbound' is not defined
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(main.py:3490685): Gdk-CRITICAL **: 15:52:16.991: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed

(main.py:3490685): Gdk-CRITICAL **: 15:52:16.992: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
360
360
360
360
360
360
360
360
360
360
360
360
360
360
360
360
360
360
360
360
360
360
360
0
0
0
0
0
0
0
0
0
0
0
134
450
573
612
1197
1197
1197
1197
1197
1197
1197
1197
1197
1197
1197
1197
1197
1197
1197
1197
1197
1197
1197
1197
1197
1197
1197
1197
1197
1197
1197
1197
1197
1197
1197
1197
1197
1197
1197
1197
1197
1197
1197
1197
1197
1197
1197
1197
1197
1197
1197
1197
1197
1197
1197
1197
1197
1197
1197
1197
1197
1197
1197
1197
1197
1197
1197
1197
1197
1197
1197
1197
1197
1197
1197
1197
1197
1197
1197
1197
1197
1197
1197
1197
1197
1197
1197
1197
1197
